version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - goconst
    - gosec
    - misspell
    - nilerr
    - revive
    - unconvert
  settings:
    goconst:
      min-len: 3
      min-occurrences: 2
    gosec:
      excludes:
        - G104
        - G101
    misspell:
      ignore-rules:
        - prompty
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: increment-decrement
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: internal/exons\.resolver\.registry\.go
        text: stutters
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
